GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "bldadg1",
  "author": "authdor1",
  "url": "randourl.com",
  "likes": 2,
  "user": "646b30e71e807f00c8e815b7"
}